version: "3.7"
services:
  koocook_dj:
    build: koocook-dj/
    container_name: koocook-dj
    restart: unless-stopped
    env_file:
      - config/dj.env
    ports:
      - "8000:8000"

  koocook-db:
    container_name: koocook-db
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - config/db.env
    ports:
      - 5432:5432