version: 2
jobs:
 build:
   machine: true
   working_directory: ~/koocook-dj
   steps:
     - checkout
     - add_ssh_keys:
         fingerprints:
           - "08:3d:2e:15:e1:c1:f6:58:5e:3d:4b:67:8e:98:59:a6"
     - run:
         name: "Pull submodules"
         command: |
           git submodule init
           git submodule update --recursive
     - run:
         name: Authenticate
         command: |
           echo "$KC_DK_PSWD" | docker login --username $KC_DK_USER --password-stdin
     - run:
         name: Build the Docker image
         command: |
           docker build -t koocook/koocook-dj:$CIRCLE_BRANCH .
     - run:
         name: Publish the Docker image
         command: |
           docker push company/app:$CIRCLE_BRANCH

 deploy:
   working_directory: ~/koocook-dj
   docker:
     - image: koocook/koocook-dj:$CIRCLE_BRANCH
       auth:
         username: $KC_DK_USER
         password: $KC_DK_PSWD
   steps:
     - checkout
     - add_ssh_keys:
         fingerprints:
           - "08:3d:2e:15:e1:c1:f6:58:5e:3d:4b:67:8e:98:59:a6"
     - run:
         name: Deploy to the GCE instance
         command: |
           ./scripts/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
