version: 2
jobs:
 build:
   machine: true
   working_directory: ~/koocook
   steps:
     - checkout
     - add_ssh_keys:
         fingerprints:
           - "32:a9:ee:b4:f6:93:d9:91:ef:42:14:cc:75:3d:c7:a5"
#     - run:
#         name: "Pull latest submodules"
#         command: |
#           git submodule init
#           git submodule update --recursive --remote
#     - run:
#         name: Authenticate into Docker Hub
#         command: |
#           echo "$KC_DK_PSWD" | docker login --username $KC_DK_USER --password-stdin
#     - run:
#         name: Build the Docker image
#         command: |
#           docker build -t koocook/koocook-dj:$DK_TAG_NAME \
#           --build-arg SOCIAL_AUTH_GOOGLE_OAUTH2_KEY \
#           --build-arg SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET \
#           --build-arg DJANGO_SECRET_KEY \
#           --build-arg DJANGO_ALLOWED_HOSTS \
#           --build-arg DATABASE_ENGINE \
#           --build-arg DATABASE_NAME \
#           --build-arg DATABASE_USERNAME \
#           --build-arg DATABASE_PASSWORD \
#           --build-arg DATABASE_PORT \
#           ./koocook-dj/
#     - run:
#         name: Publish the Docker image
#         command: |
#           docker push koocook/koocook-dj:$DK_TAG_NAME

     - run:
         name: Automate the deployment (after triggered)
         command: |
           if [ -n "${FOLLOW_WORKFLOW+x}" ]; then
                 printf "Triggering a %s deployment on the %s branch\n\n" "koocook" "$CIRCLE_BRANCH"
                 BUILD_INFO=$(curl -X POST -u "$CIRCLE_TOKEN:" \
                 -d "build_parameters[CIRCLE_JOB]=deploy" -d "build_parameters[FOLLOW_WORKFLOW]=true" \
                 "https://circleci.com/api/v1.1/project/github/KooCook/koocook/tree/$CIRCLE_BRANCH")
                 printf "\n\nBuild triggered\n\n"
                 printf "Follow the progress of the build on \nhttps://circleci.com/gh/%s/%s/tree/%s" "KooCook" "koocook" "$CIRCLE_BRANCH"
           fi
 deploy:
   working_directory: ~/koocook
   docker:
     - image: koocook/koocook-dj:$DK_TAG_NAME
       auth:
         username: $KC_DK_USER
         password: $KC_DK_PSWD
   steps:
     - checkout
     - add_ssh_keys:
         fingerprints:
           - "08:3d:2e:15:e1:c1:f6:58:5e:3d:4b:67:8e:98:59:a6"
     - run:
         name: Deploy to the GCE instance
         command: |
           sh ./scripts/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build